{% set name = "napari-micromanager" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 960ef917bbe12bb3d6829ef2af0f1fc61b28f2c6c4f46bd456a7f7b66a7f6258

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling
    - hatch-vcs
  run:
    - fonticon-materialdesignicons6
    - napari >=0.4.13
    - pymmcore-plus >=0.8.0
    - python >=3.8
    - pymmcore-widgets >=0.5.3
    - superqt >=0.5.1
    - tifffile
    - useq-schema >=0.4.1
    - zarr
    - numpy
    - qtpy

test:
  imports:
    - napari_micromanager
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pymmcore-plus/napari-micromanager
  summary: GUI interface between napari and micromanager
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - tlambert03
